# Generated by Django 6.0.3 on 2026-03-05 05:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CameraConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Default Camera", max_length=100)),
                (
                    "source",
                    models.CharField(
                        default="0",
                        help_text="Camera index (0, 1, etc.) or RTSP URL",
                        max_length=500,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Camera Configuration",
                "verbose_name_plural": "Camera Configurations",
            },
        ),
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                ("total_vehicles", models.IntegerField(default=0)),
                ("total_cars", models.IntegerField(default=0)),
                ("total_trucks", models.IntegerField(default=0)),
                ("total_buses", models.IntegerField(default=0)),
                ("total_motorcycles", models.IntegerField(default=0)),
                ("total_autos", models.IntegerField(default=0)),
                ("total_unknown", models.IntegerField(default=0)),
                ("unique_plates", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Daily Report",
                "verbose_name_plural": "Daily Reports",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="VehicleRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_plate", models.CharField(db_index=True, max_length=20)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("car", "Car"),
                            ("truck", "Truck"),
                            ("bus", "Bus"),
                            ("motorcycle", "Motorcycle"),
                            ("auto", "Auto Rickshaw"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=0.0, help_text="Detection confidence score"
                    ),
                ),
                (
                    "captured_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="captures/%Y/%m/%d/"
                    ),
                ),
                (
                    "plate_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="plates/%Y/%m/%d/"
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Vehicle Record",
                "verbose_name_plural": "Vehicle Records",
                "ordering": ["-detected_at"],
            },
        ),
    ]
