# Generated by Django 6.0.3 on 2026-03-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cameraconfig",
            options={
                "ordering": ["name"],
                "verbose_name": "Camera Configuration",
                "verbose_name_plural": "Camera Configurations",
            },
        ),
        migrations.AddField(
            model_name="cameraconfig",
            name="connection_type",
            field=models.CharField(
                choices=[
                    ("usb", "USB / Built-in Webcam"),
                    ("wifi", "WiFi Camera"),
                    ("ethernet", "Ethernet / LAN Camera"),
                    ("rtsp", "RTSP Stream"),
                    ("http", "HTTP / MJPEG Stream"),
                    ("onvif", "ONVIF Camera"),
                ],
                default="usb",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cameraconfig",
            name="detection_enabled",
            field=models.BooleanField(
                default=True, help_text="Enable vehicle detection on this camera"
            ),
        ),
        migrations.AddField(
            model_name="cameraconfig",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="cameraconfig",
            name="fps",
            field=models.IntegerField(default=15, help_text="Frames per second (5-30)"),
        ),
        migrations.AddField(
            model_name="cameraconfig",
            name="ip_address",
            field=models.CharField(
                blank=True,
                default="",
                help_text="IP address for network cameras",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="cameraconfig",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cameraconfig",
            name="location",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Physical location e.g. Main Gate, Parking Lot",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="cameraconfig",
            name="password",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Camera login password",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="cameraconfig",
            name="port",
            field=models.IntegerField(
                blank=True,
                help_text="Port number (e.g. 554 for RTSP, 80 for HTTP)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cameraconfig",
            name="resolution",
            field=models.CharField(
                blank=True,
                default="1280x720",
                help_text="Preferred resolution e.g. 1920x1080",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cameraconfig",
            name="status",
            field=models.CharField(
                choices=[
                    ("online", "Online"),
                    ("offline", "Offline"),
                    ("connecting", "Connecting"),
                    ("error", "Error"),
                ],
                default="offline",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cameraconfig",
            name="stream_path",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Stream path e.g. /stream1, /cam/realmonitor",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="cameraconfig",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="cameraconfig",
            name="username",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Camera login username",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="cameraconfig",
            name="name",
            field=models.CharField(default="Camera", max_length=100),
        ),
        migrations.AlterField(
            model_name="cameraconfig",
            name="source",
            field=models.CharField(
                default="0",
                help_text="Camera index (0,1,2..) for USB, or full URL for network cameras",
                max_length=500,
            ),
        ),
    ]
